export const menuList = [
  {
    id: 11,
    pid: 0,
    name: '任务管理',
    sort: '0',
    node: 'task',
    fullPath: 'task.*',
    sub: [
      {
        id: 13,
        pid: 11,
        name: '定时任务',
        sort: '0',
        node: 'manage',
        fullPath: 'task.manages.*',
        sub: [
          {
            id: 21,
            pid: 13,
            name: '写',
            sort: '0',
            node: 'write',
            fullPath: 'task.manages.write',
            sub: null,
          },
          {
            id: 20,
            pid: 13,
            name: '写',
            sort: '0',
            node: 'read',
            fullPath: 'task.managess.read',
            sub: null,
          },
        ],
      },
      {
        id: 12,
        pid: 11,
        name: '任务日志',
        sort: '0',
        node: 'log',
        fullPath: 'task.log.*',
        sub: [
          {
            id: 15,
            pid: 12,
            name: '读',
            sort: '0',
            node: 'read',
            fullPath: 'task.log.read',
            sub: null,
          },
          {
            id: 16,
            pid: 12,
            name: '写',
            sort: '0',
            node: 'write',
            fullPath: 'task.log.write',
            sub: null,
          },
        ],
      },
      {
        id: 14,
        pid: 11,
        name: '任务节点',
        sort: '0',
        node: 'node',
        fullPath: 'task.node.*',
        sub: [
          {
            id: 17,
            pid: 14,
            name: '读',
            sort: '0',
            node: 'read',
            fullPath: 'task.node.read',
          },
          {
            id: 19,
            pid: 14,
            name: '写',
            sort: '0',
            node: 'write',
            fullPath: 'task.node.write',
            sub: null,
          },
        ],
      },
    ],
  },
  {
    id: 22,
    pid: 0,
    name: '系统配置',
    sort: '0',
    node: 'setting',
    fullPath: 'setting.*',
    sub: [
      {
        id: 23,
        pid: 22,
        name: '用户管理',
        sort: '0',
        node: 'user',
        fullPath: 'setting.user.*',
        sub: [
          {
            id: 25,
            pid: 23,
            name: '写',
            sort: '0',
            node: 'write',
            fullPath: 'setting.user.write',
            sub: null,
          },
          {
            id: 24,
            pid: 23,
            name: '读',
            sort: '0',
            node: 'read',
            fullPath: 'setting.user.read',
            sub: null,
          },
        ],
      },
      {
        id: 24,
        pid: 22,
        name: '通知配置',
        sort: '0',
        node: 'notify-config',
        fullPath: 'setting.notify-config.*',
        sub: [
          {
            id: 25,
            pid: 24,
            name: '写',
            sort: '0',
            node: 'write',
            fullPath: 'setting.notify-config.write',
            sub: null,
          },
          {
            id: 26,
            pid: 24,
            name: '读',
            sort: '0',
            node: 'read',
            fullPath: 'setting.notify-config.read',
            sub: null,
          },
        ],
      },
      {
        id: 25,
        pid: 22,
        name: '登录日志',
        sort: '0',
        node: 'login-log',
        fullPath: 'setting.login-log.*',
        sub: [
          {
            id: 25,
            pid: 24,
            name: '写',
            sort: '0',
            node: 'write',
            fullPath: 'setting.login-log.write',
            sub: null,
          },
          {
            id: 26,
            pid: 24,
            name: '读',
            sort: '0',
            node: 'read',
            fullPath: 'setting.login-log.read',
            sub: null,
          },
        ],
      },
    ],
  },
];
