[server]
    [server.http]
        port=5921
[echo]        
    [echo.sql]
        [echo.sql.gocron]
            dsn = "go_web:93vP3xA5q6kr5UAh@tcp(111.230.134.195:4040)/gocron?charset=utf8&parseTime=True&loc=Local&readTimeout=1s&timeout=1s&writeTimeout=1s"
            maxOpenConns = 30
            maxIdleConns = 10
            connMaxLifetime = "300s"
            level = "panic"
            debug = true
[jwt]
    token="4f7fc56fd6f302aee120ad3501856098b6f9b9d5a42fcbe57b1f2d1859842c1b"                                  